export const EMAIL_IS_EMPTY = "EMAIL_IS_EMPTY";
export const PASSWORD_IS_EMPTY = "PASSWORD_IS_EMPTY";
export const USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
export const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
export const SOMETHING_HAPPENED = "SOMETHING_HAPPENED";
export const USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST';

